version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - oowlish_network
    volumes:
      - mongo-data:/data/db
  api:
    build: ./api
    container_name: api
    restart: always
    env_file:
      - api/.env
    depends_on: 
      - mongo
    ports:
      - "5000:5000"
    networks:
      - oowlish_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  web:
    build: ./client
    stdin_open: true
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - oowlish_network
networks:
  oowlish_network:
    driver: bridge
volumes:
  mongo-data:
    driver: local